version: "3.9"
services:
  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "usersdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "145Az5989"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
  redis:
    container_name: "redis"
    image: redis
    restart: always
    ports:
      - "6379:6379"
    

volumes:
  postgres-data:
